"""JSON Schema export of the wire contracts (consumed by frontend type generation)."""

from __future__ import annotations

import json
from typing import Any

from pydantic import BaseModel, TypeAdapter
from pydantic.json_schema import models_json_schema

from . import contracts as c

# Models the UI reads (serialization mode: defaults are always present on the wire).
OUTBOUND: list[type[BaseModel]] = [
    c.TaskView,
    c.AgentProgress,
    c.WsView,
    c.WsProgress,
    c.CommandReply,
    c.RepoInfo,
]
# Models the UI builds and sends (validation mode: fields with defaults are optional).
INBOUND: list[type[BaseModel]] = [
    c.StartTask,
    c.AnswerInterview,
    c.ApprovePlan,
    c.AdjustPlan,
    c.EscalationAction,
    c.CancelTask,
]


def build_schema() -> dict[str, Any]:
    _, out_schema = models_json_schema([(m, "serialization") for m in OUTBOUND], title="CrewOut")
    _, in_schema = models_json_schema([(m, "validation") for m in INBOUND], title="CrewIn")
    defs: dict[str, Any] = {**out_schema.get("$defs", {}), **in_schema.get("$defs", {})}

    ws = TypeAdapter(c.WsMessage).json_schema(mode="serialization", ref_template="#/$defs/{model}")
    cmd = TypeAdapter(c.Command).json_schema(mode="validation", ref_template="#/$defs/{model}")
    defs.update(ws.pop("$defs", {}))
    defs.update(cmd.pop("$defs", {}))
    defs["WsMessage"] = {**ws, "title": "WsMessage"}
    defs["Command"] = {**cmd, "title": "Command"}

    for name, schema in defs.items():
        _strip_nested_titles(schema, top=True)
        _require_consts(schema)
        schema["title"] = name

    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "CrewContracts",
        "description": "Generated by `crew gen-schema`. Do not edit.",
        "$defs": dict(sorted(defs.items())),
    }


def _strip_nested_titles(node: Any, top: bool = False) -> None:
    """Drop per-property titles so json2ts emits inline types instead of aliases like ``Title1``."""
    if isinstance(node, dict):
        if not top:
            node.pop("title", None)
        for key, value in node.items():
            if key in ("properties", "$defs", "patternProperties") and isinstance(value, dict):
                for sub in value.values():  # keys here are field names, not keywords
                    _strip_nested_titles(sub)
            else:
                _strip_nested_titles(value)
    elif isinstance(node, list):
        for item in node:
            _strip_nested_titles(item)


def _require_consts(schema: dict[str, Any]) -> None:
    """Literal discriminators (``type: const``) must be required so TS unions narrow."""
    props = schema.get("properties", {})
    consts = [k for k, v in props.items() if isinstance(v, dict) and "const" in v]
    if consts:
        schema["required"] = sorted(set(schema.get("required", [])) | set(consts))


def dump_schema() -> str:
    return json.dumps(build_schema(), indent=2, ensure_ascii=False) + "\n"
