/* Generated from contracts/schema.json by npm run gen:types. Do not edit. */

/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "Command".
 */
export type Command = StartTask | AnswerInterview | ApprovePlan | AdjustPlan | EscalationAction | CancelTask;
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "WsMessage".
 */
export type WsMessage = WsView | WsProgress;

/**
 * Generated by `crew gen-schema`. Do not edit.
 */
export interface CrewContracts {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "AdjustPlan".
 */
export interface AdjustPlan {
  type: "adjust_plan";
  text: string;
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "AgentProgress".
 */
export interface AgentProgress {
  agent: "interviewer" | "planner" | "developer" | "tester" | "reviewer";
  job_id: string;
  kind: "status" | "tool" | "text";
  text: string;
}
/**
 * Answers the whole pending round, in order. ``None`` accepts that question's recommendation.
 *
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "AnswerInterview".
 */
export interface AnswerInterview {
  type: "answer_interview";
  answers: (string | null)[];
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "ApprovePlan".
 */
export interface ApprovePlan {
  type: "approve_plan";
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "CancelTask".
 */
export interface CancelTask {
  type: "cancel_task";
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "StartTask".
 */
export interface StartTask {
  type: "start_task";
  repo: string;
  title: string;
  description?: string;
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "EscalationAction".
 */
export interface EscalationAction {
  type: "escalation";
  action: "instruct" | "more_attempts" | "replan";
  text?: string | null;
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "CommandReply".
 */
export interface CommandReply {
  ok: boolean;
  error: string | null;
  view: TaskView | null;
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "TaskView".
 */
export interface TaskView {
  task_id: string;
  title: string;
  description: string;
  repo: string;
  phase:
    | "interviewing"
    | "planning"
    | "awaiting_approval"
    | "developing"
    | "testing"
    | "reviewing"
    | "escalated"
    | "done"
    | "cancelled"
    | "failed";
  stages: Stages;
  edges: {
    [k: string]: "on" | "active";
  };
  active_edge: ("ma-iv" | "iv-pl" | "pl-ap" | "ap-dv" | "dv-ts" | "ts-rv" | "rv-dn" | "ts-dv" | "rv-dv") | null;
  counters: Counters;
  interview: InterviewView | null;
  plan: Plan | null;
  dev_rounds: DevResult[];
  test_runs: TestResult[];
  review: ReviewResult | null;
  escalation: Escalation | null;
  final: FinalReport | null;
  started_at: string;
  ended_at: string | null;
  cost_usd: number;
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "Stages".
 */
export interface Stages {
  manual: StageView;
  interviewer: StageView;
  planner: StageView;
  approval: StageView;
  developer: StageView;
  tester: StageView;
  reviewer: StageView;
  done: StageView;
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "StageView".
 */
export interface StageView {
  status: "idle" | "pick" | "active" | "waiting" | "done" | "error" | "skipped";
  now: string | null;
  logs: LogLine[];
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "LogLine".
 */
export interface LogLine {
  ts: string;
  text: string;
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "Counters".
 */
export interface Counters {
  dev_round: number;
  test_attempt: number;
  max_test_attempts: number;
  review_round: number;
  max_review_rounds: number;
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "InterviewView".
 */
export interface InterviewView {
  turns: InterviewTurn[];
  pending: InterviewQuestion[];
  decisions: string[];
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "InterviewTurn".
 */
export interface InterviewTurn {
  question: InterviewQuestion;
  answer: string;
  accepted_recommendation: boolean;
  round: number;
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "InterviewQuestion".
 */
export interface InterviewQuestion {
  topic: string;
  question: string;
  recommendation: string;
  options: string[];
  rationale: string | null;
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "Plan".
 */
export interface Plan {
  type: "plan";
  summary: string;
  steps: string[];
  files: PlanFile[];
  acceptance_criteria: string[];
  risks: string[];
  test_strategy: string;
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "PlanFile".
 */
export interface PlanFile {
  path: string;
  change: "A" | "M" | "D";
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "DevResult".
 */
export interface DevResult {
  type: "dev";
  round: number;
  summary: string;
  files_changed: PlanFile[];
  notes: string | null;
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "TestResult".
 */
export interface TestResult {
  type: "test";
  ok: boolean;
  passed: number;
  total: number;
  failures: TestFailure[];
  /**
   * fração 0..1 (0.87 = 87%)
   */
  coverage: number | null;
  command: string;
  tests_written: string[];
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "TestFailure".
 */
export interface TestFailure {
  test: string;
  message: string;
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "ReviewResult".
 */
export interface ReviewResult {
  type: "review";
  verdict: "approved" | "changes_requested";
  comments: ReviewComment[];
  commit_message: string | null;
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "ReviewComment".
 */
export interface ReviewComment {
  severity: "major" | "minor" | "nit";
  file: string;
  line: number | null;
  text: string;
  resolved: boolean;
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "Escalation".
 */
export interface Escalation {
  stage: "interviewer" | "planner" | "developer" | "tester" | "reviewer";
  reason: string;
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "FinalReport".
 */
export interface FinalReport {
  branch: string;
  worktree_path: string;
  files: FinalFile[];
  commit_message: string;
  duration_s: number;
  cost_usd: number;
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "FinalFile".
 */
export interface FinalFile {
  path: string;
  status: "A" | "M" | "D";
  added: number;
  removed: number;
}
/**
 * Repository as exposed to the UI (GET /api/repos).
 *
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "RepoInfo".
 */
export interface RepoInfo {
  name: string;
  base_branch: string;
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "WsView".
 */
export interface WsView {
  type: "view";
  data: TaskView | null;
}
/**
 * This interface was referenced by `CrewContracts`'s JSON-Schema
 * via the `definition` "WsProgress".
 */
export interface WsProgress {
  type: "progress";
  task_id: string;
  data: AgentProgress;
}
