"""Wire contracts shared by orchestrator, agents, gateway and UI. Frozen after M0."""

from .commands import (
    AdjustPlan,
    AnswerInterview,
    ApprovePlan,
    CancelTask,
    Command,
    CommandAdapter,
    CommandReply,
    EscalationAction,
    StartTask,
)
from .common import (
    AGENTS,
    EDGES,
    STAGES,
    TERMINAL_PHASES,
    AgentName,
    Contract,
    EdgeKey,
    EdgeStatus,
    EventSource,
    FileChange,
    StageKey,
    StageStatus,
    TaskPhase,
)
from .events import EVENT_PAYLOADS, AgentFailedEvt, AgentProgress, AgentResultEvt, Envelope, EventKind
from .jobs import AgentJob, Feedback
from .outputs import (
    AgentOutput,
    DevResult,
    InterviewQuestion,
    InterviewResult,
    InterviewTurn,
    Plan,
    PlanFile,
    ReviewComment,
    ReviewResult,
    TestFailure,
    TestResult,
)
from .task import RepoContext, RepoInfo, TaskSpec
from .view import (
    Counters,
    Escalation,
    FinalFile,
    FinalReport,
    InterviewView,
    LogLine,
    Stages,
    StageView,
    TaskView,
)
from .ws import WsMessage, WsProgress, WsView

__all__ = [
    "AGENTS",
    "EDGES",
    "EVENT_PAYLOADS",
    "STAGES",
    "TERMINAL_PHASES",
    "AdjustPlan",
    "AgentFailedEvt",
    "AgentJob",
    "AgentName",
    "AgentOutput",
    "AgentProgress",
    "AgentResultEvt",
    "AnswerInterview",
    "ApprovePlan",
    "CancelTask",
    "Command",
    "CommandAdapter",
    "CommandReply",
    "Contract",
    "Counters",
    "DevResult",
    "EdgeKey",
    "EdgeStatus",
    "Envelope",
    "Escalation",
    "EscalationAction",
    "EventKind",
    "EventSource",
    "Feedback",
    "FileChange",
    "FinalFile",
    "FinalReport",
    "InterviewQuestion",
    "InterviewResult",
    "InterviewTurn",
    "InterviewView",
    "LogLine",
    "Plan",
    "PlanFile",
    "RepoContext",
    "RepoInfo",
    "ReviewComment",
    "ReviewResult",
    "StageKey",
    "StageStatus",
    "StageView",
    "Stages",
    "StartTask",
    "TaskPhase",
    "TaskSpec",
    "TaskView",
    "TestFailure",
    "TestResult",
    "WsMessage",
    "WsProgress",
    "WsView",
]
